version: '3'
services:
    httpd-server:
        image: 'httpd'
        ports:
        -  "81-82:80"
        
        volumes:
        -  "/home/ec2-user/workspace/Project3-Sept30:/usr/local/apache2/htdocs"
